### ISSUE TITLE
How much epoch?

### ISSUE THREAD

**Issue by willer94** [SunghwanHong/CATs#1]
Hi, I trained the network on SPair-71k, and it seemed that it takes less 100 epochs to get fine result. So, how much epochs are trianed in the paper?

**Comment by SunghwanHong** [comment]
Hi! Thank you for your interest in our paper! With unfreezing the feature backbone, we also observed that it takes less than 100 epochs to attain the results reported in the paper. As a default setting, we trained 100 epochs for all the experiments in our paper, but there may be some results that do not require 100 epochs.
