### ISSUE TITLE
some questions.

### ISSUE THREAD

**Issue by 5100117** [SunghwanHong/CATs#4]
Hi, 
I am trying to understand your code. You code is very clean and well arranged I have to admit. I have a 2 questions when reading your code.
1. May I ask why you pick hyperpixel_ids=[0,8,20,21,26,28,29,30]? 
2. Have you tried other backbone other than resnet101?
By the way, do you have any advices for me to improve your code? I tried to use resnet152 as backbone, but it does not perform better than resnet101. I guess it because I used the un-optimal hyperpixel_ids.

Thank you very much.

**Comment by SunghwanHong** [comment]
Hi,
1. if you check our paper, we use different hyperpixel_ids for different datasets. Specifically, hyperpixel_ids=[0,8,20,21,26,28,29,30] is for SPair-71k found by HPF (https://github.com/juhongm999/hpf)
2. Yes, we tried using other backbones (check out our ablation study on feature backbone), but we have not tried resnet152. Have you tried training from scratch when you replaced to resnet152? if you simply replaced without training, it's highly likely that it may perform worse. If it's not the case, there may be several reasons that could result worse performance: (1) as  you mentioned, un-optimal hyperpixel_ids, (2) insufficient training epochs or could be anything else! 

We are planning to improve both the paper and code in the near future, and as soon as they are ready, we will share with the community

**Comment by 5100117** [comment]
I get it. Thank you very much.
you are awesome!
