### ISSUE TITLE
PCK evaluation on PF-Willow

### ISSUE THREAD

**Issue by PruneTruong** [SunghwanHong/CATs#6]
Hi, thanks for the great work!

I think you have an error in the PCK-threshold of PF-Willow.
It is computed as the difference between the maximum and minimum kp. However, since you always pad the kp with -1, the minimum is always -1, which is not the actual coordinate of the minimum keypoint. Therefore, the pckthreshold is artificially large and therefore the results artificially high.
I know this error is present in multiple works, for example also in DHPF. However, the comparison is not fair to methods that actually use the correct metric, like NC-Net.

**Comment by SunghwanHong** [comment]
Hi! 
Thanks for letting me know! We were not aware of it by the time when we were working on this paper. But thanks to Juhong Min and his journal extension for CHM, we are now aware of it and we are planning to reflect it including  few of other errors that Juhong told us a month ago. 
We appreciate your kindness for letting us know as well!
